-- 코드를 입력하세요
SELECT
    bgb.TITLE,
    bgb.BOARD_ID,
    bgr.REPLY_ID,
    bgr.WRITER_ID,
    bgr.CONTENTS,
    TO_CHAR(bgr.CREATED_DATE, 'YYYY-MM-DD') CREATED_DATE
FROM
    USED_GOODS_BOARD bgb
LEFT JOIN USED_GOODS_REPLY bgr
    ON bgb.BOARD_ID = bgr.BOARD_ID
WHERE 
    TO_CHAR(bgb.CREATED_DATE, 'MM') = 10
AND
    bgr.CREATED_DATE IS NOT NULL
ORDER BY bgr.CREATED_DATE ASC, bgb.TITLE ASC